/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quoteslab;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    public Object[] quoteArray;
    private quotes.App.Quote testQuote;
    private String quoteString;

    @Before
    public void initQuoteArray() throws Exception {
        quotes.App init = new quotes.App();
        new quotes.App.Quote("Richard", "hello");

        quoteString = quotes.App.getQuoteData();
        quoteArray = quotes.App.jsonToQuote(quoteString);

        testQuote = new quotes.App.Quote("Richard Rider", "Please, please, you have to, I never ask you for anything, please just do it.");
        System.out.println("Quote Array was instanced.");
    }

    @Test
    public void testQuoteToString() {

        assertNotNull("printRandom object, when run on the entire array of JSON data, should return not null.",
                quotes.App.printRandomObject(quoteArray));
    }

    @Test
    public void testQuotePrint() {

        String expectedString = "Richard Rider: Please, please, you have to, I never ask you for anything, please just do it.";

        assertEquals("printRandomObject, when run on a single object should return a string equivalent to the string above.",
                expectedString,
                quotes.App.printRandomObject(new Object[] {testQuote})
        );
    }

}
